CREATE TABLE [User] (
	Id INT NOT NULL IDENTITY(1, 1),
	Name VARCHAR(150) NOT NULL,
	Email VARCHAR(150) NOT NULL,
	Password VARCHAR(150) NOT NULL,
	
	CONSTRAINT PK_User PRIMARY KEY (Id)
);

CREATE TABLE [Student] (
	Id INT NOT NULL IDENTITY(1, 1),
	Name VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	BirthDate DATE NOT NULL,
	Sex CHAR(1) NOT NULL,
	
	CONSTRAINT PK_Student PRIMARY KEY (Id)
);

CREATE TABLE [Document] (
	Id INT NOT NULL IDENTITY(1, 1),
	Name VARCHAR(100) NOT NULL,
	Type TINYINT NOT NULL,
	Status TINYINT NOT NULL,
	Situation TINYINT NOT NULL,
	CreationDate DATETIME NOT NULL,
	
	CONSTRAINT PK_File PRIMARY KEY (Id)
);